version: '3.1'

services:

  backend:
    build: ./backend
    ports:
        - "9000:9000"


  frontend:
    build: ./frontend
    ports:
        - "8080:8080"
    depends_on:
        - backend
    environment:
        - BACKEND_DNS=backend

