version: '3.1'

services:

  backend:
    image: misterpatrick/simple-fortune-cookie-backend:k8
    ports:
        - "9000:9000"
    links:
        - redis
    depends_on:
        - redis
    environment:
        - REDIS_DNS=redis

  frontend:
    image: misterpatrick/simple-fortune-cookie-frontend:k8
    ports:
        - "8080:8080"
    depends_on:
        - backend
    environment:
        - BACKEND_DNS=backend



  redis:
    image: redis
    ports:
        - "6379:6379"
    volumes:
        - redis:/data:rw
volumes:
  redis: