apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers: 
        - env: # HER DET GÅR GALT MED BACKEND
            - name: BACKEND_DNS
              value: backend
            - name: BACKEND_PORT
              value: "9000"
          image: misterpatrick/simple-fortune-cookie-frontend:k8
          name: frontend
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
