name: Go CI
on: push

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Clone down repo
        uses: actions/checkout@v2
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: clone-down
          path: .
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Build backend
        run: go build ./backend/backend
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: build-backend
          path: .
  Test:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build-backend
          path: .
      - name: Test
        run: ./backend/backend | echo
        run: chmod+x ci/curlTest && ci/curlTest.sh
