name: Go CI
on: push

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  BACKEND_DNS: localhost
  BACKEND_PORT: 9000

jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Clone down repo
        uses: actions/checkout@v2
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: clone-down
          path: .
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: cd backend
        run: cd ./backend
      - name: Build backend
        run: go build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: backend-bin
          path: ./backend/backend
  Test:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-bin
          path: .
      - name: Start backend
        run: ./backend | echo
      - name: Test
        run: chmod+x ci/curlTest && ci/curlTest.sh
