name: Go CI
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  kube_config: ${{ secrets.KUBE_CONFIG}}

jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Clone down repo
        uses: actions/checkout@v2
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: clone-down
          path: .

  DockerImage-frontend:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download artifact clone-down
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./frontend
          tags: ${{ env.docker_username }}/simple-fortune-cookie-frontend:${{ github.sha }}

  DockerImage-backend:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download artifact clone-down
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./backend
          tags: ${{ env.docker_username }}/simple-fortune-cookie-backend:${{ github.sha }}

  Go-Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Run Go Test on frontend
        run: go test
        working-directory: ./frontend
    
  deployment:
    needs: [Clone-down, DockerImage-frontend, DockerImage-backend, Go-Test]
    runs-on: ubuntu-latest
    steps:
      - name: Make .kube dir
        run: mkdir ./.kube
        working-directory: .
      - name: Get kubeconfig contents
        run: echo "$env.kube_config" > ./config.txt 
      - name: catting config
        run: cat ./config.txt
      - name: Decode kubeconfig
        run: cat ./config.txt | base64 -d > ./.kube/config
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Set new backend image
        run: kubectl set image backend=misterpatrick/simple-fortune-cookie-backend:${{ github.sha }} -f ./simple-fortune-cookie/k8s/backend-deployment.yaml 
      - name: Set new frontend image
        run: kubectl set image frontend=misterpatrick/simple-fortune-cookie-frontend:${{ github.sha }} -f ./simple-fortune-cookie/k8s/frontend-deployment.yaml 

