name: Go CI
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  BACKEND_DNS: localhost
  BACKEND_PORT: 9000

jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Clone down repo
        uses: actions/checkout@v2
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: clone-down
          path: .
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Build backend
        run: go build
        working-directory: ./backend
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: backend-bin
          path: ./backend/backend
  Go-Test:
    needs: Build
    runs-on: ubuntu-latests
    container: golang:latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Run Go Test on frontend
        run: go test
        working-directory: ./frontend