name: Go CI
on: 
  push:
  pull_request:
    branches:
      - main


env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  BACKEND_DNS: localhost
  BACKEND_PORT: 9000

jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Clone down repo
        uses: actions/checkout@v2
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: clone-down
          path: .
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Build backend
        run: go build
        working-directory: ./backend
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: backend-bin
          path: ./backend/backend
      - name: Build frontend
        run: go build
        working-directory: ./frontend
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: frontend-bin
          path: ./frontend/frontend
  Go-Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Run Go Test on frontend
        run: go test
        working-directory: ./frontend
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Clone-down, Build, Test]
    steps:
      - name: Download artifact clone-down
        uses: actions/download-artifact@v2
        with:
          name: clone-down
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: misterpatrick/simple-fortune-cookie:latest

